name: NyoomCarts
version: '${version}'
main: dev.onesix.nyoomcarts.NyoomCartsPlugin
api-version: '1.20'
authors: [ '0b10000' ]
libraries:
  - dev.dejvokep:boosted-yaml-spigot:1.3
softdepend:
  - NoteBlockAPI
permissions:
  nyoomcarts.sign:
    description: "Allows players to place NyoomCarts signs"
    default: op