name: Java main CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: "Plugin JAR"
          path: ${{ github.workspace }}/build/libs/NyoomCarts-*.jar
      - uses: "marvinpinto/action-automatic-releases@latest"
        if: github.event_name != 'pull_request'
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Latest development build (may be unstable)"
          files: |
            ${{ github.workspace }}/NOTICE
            ${{ github.workspace }}/LICENSE
            ${{ github.workspace }}/build/libs/NyoomCarts-*.jar
